// Generated by CoffeeScript 1.3.3
(function() {
  var BurstQueue, exports;

  BurstQueue = (function() {
    var _availableCalls, _counter, _maxItems, _queue;

    _queue = new Array();

    _counter = 0;

    _maxItems = 0;

    _availableCalls = 0;

    function BurstQueue(itemsPerPeriod, period) {
      _availableCalls = _maxItems = itemsPerPeriod;
      setInterval(this.process, period);
    }

    BurstQueue.prototype.add = function(callbacks) {
      var callback, ids, _i, _len;
      if (Object.prototype.toString.apply(callbacks) === '[object Array]') {
        ids = new Array();
        for (_i = 0, _len = callbacks.length; _i < _len; _i++) {
          callback = callbacks[_i];
          console.log(callback);
          if (_availableCalls > 0) {
            _availableCalls--;
            callback();
          } else {
            _queue.push({
              id: _counter,
              callback: callback
            });
          }
          ids.push(_counter++);
        }
        return ids;
      } else {
        if (_availableCalls > 0) {
          _availableCalls--;
          callbacks();
        } else {
          _queue.push({
            id: _counter,
            callback: callbacks
          });
        }
        return _counter++;
      }
    };

    BurstQueue.prototype.clear = function() {
      _queue.length = 0;
      return _availableCalls = _maxItems;
    };

    BurstQueue.prototype.counter = function() {
      return _counter;
    };

    BurstQueue.prototype.enqueued = function() {
      return _queue.length;
    };

    BurstQueue.prototype.process = function() {
      var index, _i, _ref;
      if (_queue.length < 1) {
        _availableCalls = _maxItems;
        return;
      }
      for (index = _i = 0, _ref = _queue.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; index = 0 <= _ref ? ++_i : --_i) {
        _queue[index].callback();
        if ((index + 1) >= _maxItems) {
          break;
        }
      }
      _queue.splice(0, index + 1);
      if (index < _maxItems) {
        return _availableCalls = _maxItems - (index + 1);
      }
    };

    BurstQueue.prototype.remove = function(id) {
      var index, success, _i, _ref;
      if (_queue.length < 1) {
        return false;
      }
      success = false;
      for (index = _i = 0, _ref = _queue.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; index = 0 <= _ref ? ++_i : --_i) {
        if (_queue[index].id === id) {
          success = true;
          break;
        }
      }
      if (success) {
        _queue.splice(index, 1);
      }
      return success;
    };

    BurstQueue.prototype.availableCalls = function() {
      return _availableCalls;
    };

    return BurstQueue;

  })();

  exports = module.exports;

  exports.createQueue = function(itemsPerPeriod, period) {
    return new BurstQueue(itemsPerPeriod, period);
  };

}).call(this);
